#!/bin/bash

echo "Hauràs d'executar l'script sense sudo per a poder visualitzar en format HTML!"

ipserv=""
hostname=""

establir_connexio_ssh() {
	while true; do
    	echo "Introdueix el nom de l'equip al que et vols connectar:"
    	read -p "> " hostname

    	echo "Introdueix la direcció IP del servidor:"
    	read -p "> " ipserv

    	echo "Establint connexió SSH a $hostname - $ipserv"

    	# Generar par de claves SSH si no existe
    	if [ ! -f ~/.ssh/id_rsa ]; then
        	ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
    	fi

    	# Copiar clave pública al servidor remoto
    	ssh-copy-id $hostname@$ipserv >/dev/null 2>&1

    	# Verificar la conexión SSH
    	if ssh $hostname@$ipserv exit >/dev/null 2>&1; then
        	echo "Connexió SSH establerta a $hostname - $ipserv"
        	instnmap
        	return 0
    	else
        	echo "No s'ha pogut establir la connexió SSH a $hostname - $ipserv. Torna-ho a intentar."
    	fi
	done
}

trampactrl_c() {
	echo "Has fet un Ctrl + C. Sortint del script"
	exit 1
}

trap trampactrl_c SIGINT

instnmap() {
	echo "Comprovant si nmap ja està instal·lat"
	if ! ssh $hostname@$ipserv 'command -v nmap' &>/dev/null; then
    	echo "nmap no està instal·lat, s'instal·larà"

    	echo "Introdueix la contrasenya del servidor per a la instal·lació de nmap:"
    	read -s password

    	ssh $hostname@$ipserv "echo $password | sudo -S apt update && echo $password | sudo -S apt install -y nmap"
	else
    	echo "nmap ja està instal·lat!"
	fi
}

while ! establir_connexio_ssh; do
	:
done

usuari=$(whoami)

connssh="ssh -o PasswordAuthentication=no $hostname@$ipserv"

maquinari=$(cat << maquinari_EOF
echo "<h3>Informació del Hardware:</h3><br>"
lscpu
echo "------------------------------------------------------------------------"
echo "<h3>Informació de l'emmagatzematge:</h3><br>"
lsblk
echo "------------------------------------------------------------------------"
echo "<h3>Ús del disc:</h3><br>"
df -h
echo "------------------------------------------------------------------------"
maquinari_EOF
)

nmap=$(cat << nmap_EOF
nmap -p- -Pn $ipserv | grep -E '^[0-9]+\/(tcp|udp)' | awk '{print \$1}'
nmap_EOF
)

comprovar_ports() {
	echo "Comprovant ports"
	ports=$($connssh "$nmap")
}

comprovar_serveis() {
	echo "Comprovant serveis oberts"
	services=$($connssh 'systemctl list-units --type=service --state=active' | awk '{print $1}')
}

comprovar_intern() {
	echo "Comprovant maquinari i programari del servidor (H/S)"
	maquinari=$($connssh "$maquinari")
}

trap 'echo "Error al script!" && exit 1' ERR

comprovar_ports
comprovar_serveis
comprovar_intern

cat << EOF > moongirl.html
<!DOCTYPE html>
<html>
<head>
	<title>Serveis actius al servidor remot</title>
</head>
<body>
	<h1>Ports oberts al remot:</h1>
	<pre>
	$ports
	</pre>
    
	<h1>Serveis oberts al servidor remot:</h1>
	<pre>
	$services
	</pre>
    
	<h1>Maquinari del remot (H/S)</h1>
	<pre>
	$maquinari
	</pre>
</body>
</html>
EOF

scp moongirl.html $hostname@$ipserv:/home/$hostname/moongirl.html

echo "Fitxer transferit al remot per capturar informació"

scp $hostname@$ipserv:/home/$hostname/moongirl.html /home/$usuari/moongirl.html

echo "Fitxer moongirl.html descarregat aquí, el pots trobar a la carpeta de l'usuari (/home/usuari/moongirl.html)"




